/*global systemDictionary:true */
'use strict'

systemDictionary = {
  'elero-usb-transmitter adapter settings': {
    en: 'Adapter settings for elero-usb-transmitter',
    de: 'Adaptereinstellungen für elero-usb-transmitter',
    ru: 'Настройки адаптера для elero-usb-transmitter',
    pt: 'Configurações do adaptador para elero-usb-transmitter',
    nl: 'Adapterinstellingen voor elero-usb-transmitter',
    fr: "Paramètres d'adaptateur pour elero-usb-transmitter",
    it: "Impostazioni dell'adattatore per elero-usb-transmitter",
    es: 'Ajustes del adaptador para elero-usb-transmitter',
    pl: 'Ustawienia adaptera dla elero-usb-transmitter',
    'zh-cn': 'elero-usb-transmitter的适配器设置',
  },
  'Main settings': {
    en: 'Main settings',
    de: 'Haupteinstellungen',
    ru: 'option1',
    pt: 'option1',
    nl: 'option1',
    fr: 'option1',
    it: 'option1',
    es: 'option1',
    pl: 'option1',
    'zh-cn': 'option1',
  },
  'Device settings': {
    en: 'Device settings',
    de: 'Geräteeinstellungen',
    ru: 'option1',
    pt: 'option1',
    nl: 'option1',
    fr: 'option1',
    it: 'option1',
    es: 'option1',
    pl: 'option1',
    'zh-cn': 'option1',
  },
  usbStickDevicePath: {
    en: 'USB stick device path',
    de: 'USB Stick Geräte Pfad',
    ru: 'option1',
    pt: 'option1',
    nl: 'option1',
    fr: 'option1',
    it: 'option1',
    es: 'option1',
    pl: 'option1',
    'zh-cn': 'option1',
  },
  refreshInterval: {
    en: 'Refresh interval',
    de: 'Aktualisierungsinterval',
    ru: 'option1',
    pt: 'option1',
    nl: 'option1',
    fr: 'option1',
    it: 'option1',
    es: 'option1',
    pl: 'option1',
    'zh-cn': 'option1',
  },
}
